### ISSUE TITLE
Segmentation fault after updating curl to 7.65.0-2

### ISSUE THREAD

**Issue by SakuraLife** [falconindy/auracle#54]
After the update the libcurl, the auracle is fault.
I test it with `auracle sync`. This is the stack info:
```
#0  0x00007ffff7dddfce in ?? () from /usr/lib/libcurl.so.4
#1  0x00007ffff7dde2a5 in curl_multi_socket_action () from /usr/lib/libcurl.so.4
#2  0x00005555555d1c93 in aur::Aur::OnCurlIO (fd=8, revents=1, userdata=0x7fffffffe080) at ../src/aur/aur.cc:284
#3  0x00007ffff7d3fc00 in ?? () from /usr/lib/libsystemd.so.0
#4  0x00007ffff7d40210 in sd_event_dispatch () from /usr/lib/libsystemd.so.0
#5  0x00007ffff7d441b9 in sd_event_run () from /usr/lib/libsystemd.so.0
#6  0x00005555555d2240 in aur::Aur::Wait (this=0x7fffffffe080) at ../src/aur/aur.cc:399
#7  0x0000555555570df9 in auracle::Auracle::Sync (this=0x7fffffffe080, args=std::vector of length 0, capacity 0, options=...) at ../src/auracle/auracle.cc:634
#8  0x00005555555664f6 in main (argc=2, argv=0x7fffffffe528) at ../src/auracle_main.cc:249
```
The previous version of curl is 7.65.0-2 works well, but the new version 7.65.1-1 is not.

**Comment by falconindy** [comment]
Works for me. Probably https://github.com/curl/curl/issues/3995.

Not an Auracle problem.

**Comment by falconindy** [comment]
For the sake of helping upstream curl, could you please update to testing/curl-7.65.1-2 and see if that resolves your problem?

**Comment by SakuraLife** [comment]
I didn't find the testing/curl package.So I use curl-git instead and it solved my problem. I think the upstream has solved it.

**Comment by falconindy** [comment]
Ah, that's my fault for updating SVN but not actually pushing it the repos  (fixed now). Thanks for testing from git.

**Comment by Jesin** [comment]
This still happens with `testing/curl-7.65.1-2`. I guess I'll try updating curl from git.

**Comment by Jesin** [comment]
This still happens even with `curl-git-7.65.1.26.g29177f422`. I built `curl-git` and `auracle-git` with debug symbols. Here's the core dump: [auracle-sync-2019-06-11-5111.core.gz](https://github.com/falconindy/auracle/files/3277650/auracle-sync-2019-06-11-5111.core.gz)

**Comment by falconindy** [comment]
It's not useful to provide a coredump for an AUR package, because I don't have an identical binary -- you haven't mentioned what version of auracle this is.

Can you please just provide the stack trace?

**Comment by Jesin** [comment]
Oh sorry, I thought that fit the description of the "symbolized coredump" you requested in #55. Anyway, here's the stack trace:
```
Process 5111 (auracle) of user 1000 dumped core.                              

Stack trace of thread 5111:                                                                                                                                                                                             
#0  0x00007f938d3429bf multi_socket (libcurl.so.4)                            
#1  0x00007f938d342d04 curl_multi_socket_action (libcurl.so.4)                                                                                                                                                          
#2  0x0000560bc17995b1 _ZN3aur3Aur8OnCurlIOEP15sd_event_sourceijPv (auracle)
#3  0x00007f938d2b36b0 n/a (libsystemd.so.0)                 
#4  0x00007f938d2b4e0f sd_event_dispatch (libsystemd.so.0)               
#5  0x00007f938d2ba229 sd_event_run (libsystemd.so.0)                                                                                                                                                                   
#6  0x0000560bc1797bf8 _ZN3aur3Aur4WaitEv (auracle)                                                                                                                                                                     
#7  0x0000560bc176c012 _ZN7auracle7Auracle4SyncERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERKNS0_14CommandOptionsE (auracle)
#8  0x0000560bc175af43 main (auracle)                                                                                                                                                                                   
#9  0x00007f938ced9ee3 __libc_start_main (libc.so.6)                                                                                                                                                                    
#10 0x0000560bc175b2be _start (auracle)
```
If you'd like a copy of the binary and/or any of the `.so` files it pulled in, I can provide that too. Just let me know.

**Comment by falconindy** [comment]
So this is still a problem with curl. They're aware of the presence of segfaults in master, e.g. https://github.com/curl/curl/issues/4012 and https://github.com/curl/curl/issues/3991.

**Comment by Jesin** [comment]
This appears to be fixed as of curl/curl@6cc18c59a77bccdd04f65a9abcc9a2b2f88d368d.
